:name: twitch
:long-name: Twitch Network Analysis
:description: Learn how to perform a network analysis by using Cypher and Graph Data Science algorithms
//:icon: documentation/img/icij-logo.png
:tags: example-data,dataset,network-analysis,graph-data-science,twitch
:author: Tomaz Bratanic
:demodb: true
:data: false
:use-load-script: false
:use-dump-file: data/twitch-40.dump
:zip-file: false
:use-plugin: gds,apoc
:target-db-version: 4.2.1
//:bloom-perspective: bloom/icij-panama-papers.bloom-perspective
:guide: documentation/twitch.neo4j-browser-guide
:rendered-guide: https://guides.neo4j.com/sandbox/{name}/index.html
:model: documentation/img/graph-model.png
:example: documentation/img/example.png
:nodes: 4680870
:relationships: 10076938

//:todo: false
//image::{icon}[width=100]

== {long-name} Graph Example

Description: _{description}_

_NOTE: Due to the size of the data files, you will need `git-lfs` installed to clone this repository. You can install the tool via homebrew and other package managers, or you can download the library. For more details, see Github’s https://git-lfs.github.com/[page] for information on git-lfs._

ifeval::[{todo} != false]
To Do: {todo}
endif::[]

Nodes {nodes} Relationships {relationships}

.Model
image::{model}[]

.Example
image::{example}[width=600]

.Example Query:
[source,cypher,role=query-example, param-name=streamer,param-value="ludwig",result-column=moderator_or_vip,expected-result="qtcinderella"]
----
MATCH (s:Stream{name:$streamer})<-[:VIP|:MODERATOR]-(user)
RETURN user.name as moderator_or_vip LIMIT 20
----

=== Setup

This is for Neo4j version: {target-db-version}

ifeval::[{use-plugin} != false]
Required plugins: {use-plugin}
endif::[]

ifeval::[{demodb} != false]
The database is also available on https://demo.neo4jlabs.com:7473

Username "{name}", password: "{name}", database: "{name}"
endif::[]

Rendered guide available via: `:play {rendered-guide}`

Unrendered guide: link:{guide}[]

Load graph data via the following:

ifeval::[{data} != false]
==== Data files: `{data}`

Import flat files (csv, json, etc) using Cypher's https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[`LOAD CSV`], https://neo4j.com/labs/apoc/[APOC library], or https://neo4j.com/developer/data-import/[other methods].
endif::[]

ifeval::[{use-dump-file} != false]
==== Dump file: `{use-dump-file}`

* Drop the file into the `Files` section of a project in Neo4j Desktop. Then choose the option to `Create new DBMS from dump` option from the file options.

* Use the neo4j-admin tool to load data from the command line with the command below.

[source,shell,subs=attributes]
----
bin/neo4j-admin load --from {use-dump-file} [--database "database"]
----

* Upload the dump file to Neo4j Aura via https://console.neo4j.io/#import-instructions
endif::[]

ifeval::[{use-load-script} != false]
==== Data load script: `{use-load-script}`

[source,shell,subs=attributes]
----
bin/cypher-shell -u neo4j -p "password" -f {use-load-script} [-d "database"]
----

Or import in Neo4j Browser by dragging or pasting the content of {use-load-script}.
endif::[]

ifeval::[{zip-file} != false]
==== Zip file

Download the zip file link:{repo}/raw/master/{name}.zip[{name}.zip] and add it as "project from file" to https://neo4j.com/developer/neo4j-desktop[Neo4j Desktop^].
endif::[]

=== Code Examples

* link:code/javascript/example.js[JavaScript]
* link:code/java/Example.java[Java]
* link:code/csharp/Example.cs[C#]
* link:code/python/example.py[Python]
* link:code/go/example.go[Go]

=== Feedback

Feel free to submit issues or pull requests for improvement on this repository.

